#!/bin/bash
# 离线版 build-server 脚本
set -ex

source $(dirname $0)/version
source $(dirname $0)/export-config

cd $(dirname $0)/..

mkdir -p bin

if [ -n "${DEBUG}" ]; then
  GCFLAGS="-N -l"
fi

if [ "$(uname)" != "Darwin" ]; then
  LINKFLAGS="-extldflags -static"
  if [ -z "${DEBUG}" ]; then
    LINKFLAGS="${LINKFLAGS} -s"
  fi
fi

RKE_VERSION="$(grep -m1 'github.com/rancher/rke' go.mod | awk '{print $2}')"

# Inject Setting values
DEFAULT_VALUES="{\"rke-version\":\"${RKE_VERSION}\"}"

# 离线模式：禁用网络访问
export GOPROXY=off
export GOFLAGS=-mod=vendor

CGO_ENABLED=0 go build -tags k8s \
  -gcflags="all=${GCFLAGS}" \
  -ldflags \
  "-X github.com/rancher/rancher/pkg/version.Version=$VERSION
   -X github.com/rancher/rancher/pkg/version.GitCommit=$COMMIT
   -X github.com/rancher/rancher/pkg/settings.InjectDefaults=$DEFAULT_VALUES $LINKFLAGS" \
  -o bin/rancher

# 使用本地的 data.json
if [ -e resources/kdm/data.json ]; then
    cp resources/kdm/data.json bin/data.json
elif [ -e bin/data.json ]; then
    echo "Using existing bin/data.json"
else
    echo "ERROR: data.json not found!"
    exit 1
fi
